2025-04-30 11:26:17,704 - product_materials.py:[42] - [ERROR] - 请求发生错误: 401 Client Error: Unauthorized for url: http://192.168.0.135:8282/MaterialInfoApi/StoreMaterialInfoData，请求URL: http://192.168.0.135:8282/MaterialInfoApi/StoreMaterialInfoData，请求头: {'authorization': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxMDQwMiIsIlVzZXJDb2RlIjoiQ1EiLCJVc2VyTmFtZSI6IumZiOW8uiIsIlVzZXJUeXBlIjoiMSIsIkNvbXBhbnlDb2RlIjoiMDAwMDAiLCJGYWN0b3J5Q29kZSI6IjAwMDAwLjAwMDAxIiwiSXAiOiIxOTIuMTY4LjgyLjIwNCIsIk9yZ2FuaXphdGlvblN0cnVjdHVyZUNvZGUiOiIwMDAwMC4wMDAwMSIsImV4cCI6MTc0NjUxMTQ2MCwiaXNzIjoiUmguTWVzIiwiYXVkIjoiUmguTWVzLlNlcnZpY2VzIn0.qJTBRisMp1IY_KQA4D5swkGKEsgUtH_SRhf7BR7VUdM '}，请求体: {'MaterialCode': 'Automation01', 'MaterialName': '自动化测试物料01', 'materialCharacteristic': [{'label': '成品'}, {'label': '半成品'}, {'label': '物料'}], 'MaterialCategoryCode': 'DQJ', 'MaterialAttribute': 'SelfCreated', 'MaterialSpecification': '', 'OpSign': 1, 'MaintainerId': 10402, 'MaintainerName': 'CQ'}
2025-04-30 13:53:48,716 - product_materials.py:[45] - [ERROR] - 请求发生错误: Value for header {authorization: <function get_token at 0x000001FCDC26A7B8>} must be of type str or bytes, not <class 'function'>，请求URL: http://192.168.0.135:8282/MaterialInfoApi/StoreMaterialInfoData，请求头: {'authorization': <function get_token at 0x000001FCDC26A7B8>}，请求体: {'MaterialCode': 'Automation01', 'MaterialName': '自动化测试物料01', 'materialCharacteristic': [{'label': '成品'}, {'label': '半成品'}, {'label': '物料'}], 'MaterialCategoryCode': 'DQJ', 'MaterialAttribute': 'SelfCreated', 'MaterialSpecification': '', 'OpSign': 1, 'MaintainerId': 10402, 'MaintainerName': 'CQ'}
2025-04-30 13:54:36,353 - product_materials.py:[46] - [ERROR] - 请求发生错误: 401 Client Error: Unauthorized for url: http://192.168.0.135:8282/MaterialInfoApi/StoreMaterialInfoData，请求URL: http://192.168.0.135:8282/MaterialInfoApi/StoreMaterialInfoData，请求头: {'authorization': 'BearereyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxMDQwMiIsIlVzZXJDb2RlIjoiQ1EiLCJVc2VyTmFtZSI6IumZiOW8uiIsIlVzZXJUeXBlIjoiMSIsIkNvbXBhbnlDb2RlIjoiMDAwMDAiLCJGYWN0b3J5Q29kZSI6IjAwMDAwLjAwMDAxIiwiSXAiOiIxOTIuMTY4LjgyLjIwNCIsIk9yZ2FuaXphdGlvblN0cnVjdHVyZUNvZGUiOiIwMDAwMC4wMDAwMSIsImV4cCI6MTc0NjU5NzI3NSwiaXNzIjoiUmguTWVzIiwiYXVkIjoiUmguTWVzLlNlcnZpY2VzIn0.Wv5dBWfAjEH-GmSQBMQJPY9SE-YLdE_-1VmDTjkHPAo'}，请求体: {'MaterialCode': 'Automation01', 'MaterialName': '自动化测试物料01', 'materialCharacteristic': [{'label': '成品'}, {'label': '半成品'}, {'label': '物料'}], 'MaterialCategoryCode': 'DQJ', 'MaterialAttribute': 'SelfCreated', 'MaterialSpecification': '', 'OpSign': 1, 'MaintainerId': 10402, 'MaintainerName': 'CQ'}
2025-04-30 13:54:48,049 - product_materials.py:[46] - [ERROR] - 请求发生错误: 401 Client Error: Unauthorized for url: http://192.168.0.135:8282/MaterialInfoApi/StoreMaterialInfoData，请求URL: http://192.168.0.135:8282/MaterialInfoApi/StoreMaterialInfoData，请求头: {'authorization': 'BearereyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxMDQwMiIsIlVzZXJDb2RlIjoiQ1EiLCJVc2VyTmFtZSI6IumZiOW8uiIsIlVzZXJUeXBlIjoiMSIsIkNvbXBhbnlDb2RlIjoiMDAwMDAiLCJGYWN0b3J5Q29kZSI6IjAwMDAwLjAwMDAxIiwiSXAiOiIxOTIuMTY4LjgyLjIwNCIsIk9yZ2FuaXphdGlvblN0cnVjdHVyZUNvZGUiOiIwMDAwMC4wMDAwMSIsImV4cCI6MTc0NjU5NzI4NywiaXNzIjoiUmguTWVzIiwiYXVkIjoiUmguTWVzLlNlcnZpY2VzIn0.idl0Bad5SCUoYSdpefIZZrtJAqrRQWuV1_oqFu30GTg'}，请求体: {'MaterialCode': 'Automation01', 'MaterialName': '自动化测试物料01', 'materialCharacteristic': [{'label': '成品'}, {'label': '半成品'}, {'label': '物料'}], 'MaterialCategoryCode': 'DQJ', 'MaterialAttribute': 'SelfCreated', 'MaterialSpecification': '', 'OpSign': 1, 'MaintainerId': 10402, 'MaintainerName': 'CQ'}
2025-04-30 14:22:44,444 - product_materials.py:[46] - [ERROR] - 请求发生错误: Invalid return character or leading space in header: authorization，请求URL: http://192.168.0.135:8282/MaterialInfoApi/StoreMaterialInfoData，请求头: {'authorization': 'Bearer\neyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxMDQxOCIsIlVzZXJDb2RlIjoiemRoMDEiLCJVc2VyTmFtZSI6IuiHquWKqOWMlua1i-ivleS4k-eUqOi0puWPt--8iOWLv-WKqO-8iSIsIlVzZXJUeXBlIjoiMSIsIkNvbXBhbnlDb2RlIjoiMDAwMDAiLCJGYWN0b3J5Q29kZSI6IiIsIklwIjoiMTkyLjE2OC44Mi4yMDQiLCJPcmdhbml6YXRpb25TdHJ1Y3R1cmVDb2RlIjoiMDAwMDAuMDAwMDEiLCJleHAiOjE3NDY1OTg5NjQsImlzcyI6IlJoLk1lcyIsImF1ZCI6IlJoLk1lcy5TZXJ2aWNlcyJ9.i3TgymHKaAKNQHtNpeU_WmpXq2uNpRlwoQkNyjiW4gA'}，请求体: {'MaterialCode': 'Automation01', 'MaterialName': '自动化测试物料01', 'materialCharacteristic': [{'label': '成品'}, {'label': '半成品'}, {'label': '物料'}], 'MaterialCategoryCode': 'DQJ', 'MaterialAttribute': 'SelfCreated', 'MaterialSpecification': '', 'OpSign': 1, 'MaintainerId': 10402, 'MaintainerName': 'CQ'}
2025-04-30 14:28:14,408 - product_materials.py:[46] - [ERROR] - 请求发生错误: Invalid return character or leading space in header: authorization，请求URL: http://192.168.0.135:8282/MaterialInfoApi/StoreMaterialInfoData，请求头: {'authorization': 'Bearer\neyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxMDQxOCIsIlVzZXJDb2RlIjoiemRoMDEiLCJVc2VyTmFtZSI6IuiHquWKqOWMlua1i-ivleS4k-eUqOi0puWPt--8iOWLv-WKqO-8iSIsIlVzZXJUeXBlIjoiMSIsIkNvbXBhbnlDb2RlIjoiMDAwMDAiLCJGYWN0b3J5Q29kZSI6IiIsIklwIjoiMTkyLjE2OC44Mi4yMDQiLCJPcmdhbml6YXRpb25TdHJ1Y3R1cmVDb2RlIjoiMDAwMDAuMDAwMDEiLCJleHAiOjE3NDY1OTkyOTMsImlzcyI6IlJoLk1lcyIsImF1ZCI6IlJoLk1lcy5TZXJ2aWNlcyJ9.TH_kUgJxI_ncOdKElo4V1V3YSzOGyJWYua2wFo-UpZw'}，请求体: {'MaterialCode': 'Automation01', 'MaterialName': '自动化测试物料01', 'materialCharacteristic': [{'label': '成品'}, {'label': '半成品'}, {'label': '物料'}], 'MaterialCategoryCode': 'DQJ', 'MaterialAttribute': 'SelfCreated', 'MaterialSpecification': '', 'OpSign': 1, 'MaintainerId': 10402, 'MaintainerName': 'CQ'}
2025-04-30 14:42:12,081 - product_materials.py:[98] - [ERROR] - 请求发生错误: Invalid URL 'your_validation_url': No scheme supplied. Perhaps you meant http://your_validation_url?
2025-04-30 14:42:12,246 - product_materials.py:[98] - [ERROR] - 请求发生错误: Invalid URL 'your_validation_url': No scheme supplied. Perhaps you meant http://your_validation_url?
2025-04-30 14:42:12,411 - product_materials.py:[98] - [ERROR] - 请求发生错误: Invalid URL 'your_validation_url': No scheme supplied. Perhaps you meant http://your_validation_url?
2025-04-30 14:42:12,411 - product_materials.py:[100] - [ERROR] - 多次尝试后仍无法获取有效的 authorization。
2025-04-30 14:47:50,740 - product_materials.py:[46] - [ERROR] - 请求发生错误: Invalid return character or leading space in header: authorization，请求URL: http://192.168.0.135:8282/MaterialInfoApi/StoreMaterialInfoData，请求头: {'authorization': 'Bearer\neyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxMDQxOCIsIlVzZXJDb2RlIjoiemRoMDEiLCJVc2VyTmFtZSI6IuiHquWKqOWMlua1i-ivleS4k-eUqOi0puWPt--8iOWLv-WKqO-8iSIsIlVzZXJUeXBlIjoiMSIsIkNvbXBhbnlDb2RlIjoiMDAwMDAiLCJGYWN0b3J5Q29kZSI6IiIsIklwIjoiMTkyLjE2OC44Mi4yMDQiLCJPcmdhbml6YXRpb25TdHJ1Y3R1cmVDb2RlIjoiMDAwMDAuMDAwMDEiLCJleHAiOjE3NDY2MDA0NzAsImlzcyI6IlJoLk1lcyIsImF1ZCI6IlJoLk1lcy5TZXJ2aWNlcyJ9.bxBdDLPmxDfP0oSG9zSWNdwnshWJ4eF1V-OVq-D-l7o'}，请求体: {'MaterialCode': 'Automation01', 'MaterialName': '自动化测试物料01', 'materialCharacteristic': [{'label': '成品'}, {'label': '半成品'}, {'label': '物料'}], 'MaterialCategoryCode': 'DQJ', 'MaterialAttribute': 'SelfCreated', 'MaterialSpecification': '', 'OpSign': 1, 'MaintainerId': 10402, 'MaintainerName': 'CQ'}
2025-04-30 14:51:20,232 - product_materials.py:[46] - [ERROR] - 请求发生错误: Invalid return character or leading space in header: authorization，请求 URL: http://192.168.0.135:8282/MaterialInfoApi/StoreMaterialInfoData，请求头: {'authorization': 'Bearer\neyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiIxMDQxOCIsIlVzZXJDb2RlIjoiemRoMDEiLCJVc2VyTmFtZSI6IuiHquWKqOWMlua1i-ivleS4k-eUqOi0puWPt--8iOWLv-WKqO-8iSIsIlVzZXJUeXBlIjoiMSIsIkNvbXBhbnlDb2RlIjoiMDAwMDAiLCJGYWN0b3J5Q29kZSI6IiIsIklwIjoiMTkyLjE2OC44Mi4yMDQiLCJPcmdhbml6YXRpb25TdHJ1Y3R1cmVDb2RlIjoiMDAwMDAuMDAwMDEiLCJleHAiOjE3NDY2MDA2NzksImlzcyI6IlJoLk1lcyIsImF1ZCI6IlJoLk1lcy5TZXJ2aWNlcyJ9.k7LMPjALNhdyaJ_kbFAh_05PcS2G8FVQUhCemW07Ah4'}，请求体: {'MaterialCode': 'Automation01', 'MaterialName': '自动化测试物料01', 'materialCharacteristic': [{'label': '成品'}, {'label': '半成品'}, {'label': '物料'}], 'MaterialCategoryCode': 'DQJ', 'MaterialAttribute': 'SelfCreated', 'MaterialSpecification': '', 'OpSign': 1, 'MaintainerId': 10402, 'MaintainerName': 'CQ'}
2025-04-30 14:54:33,113 - get_token.py:[49] - [ERROR] - 请求发生错误: Invalid URL 'your_validation_url': No scheme supplied. Perhaps you meant http://your_validation_url?
2025-04-30 14:54:33,275 - get_token.py:[49] - [ERROR] - 请求发生错误: Invalid URL 'your_validation_url': No scheme supplied. Perhaps you meant http://your_validation_url?
2025-04-30 14:54:33,441 - get_token.py:[49] - [ERROR] - 请求发生错误: Invalid URL 'your_validation_url': No scheme supplied. Perhaps you meant http://your_validation_url?
2025-04-30 14:54:33,441 - get_token.py:[51] - [ERROR] - 多次尝试后仍无法获取有效的 authorization。
2025-04-30 14:54:33,453 - product_materials.py:[45] - [ERROR] - 请求发生错误: 401 Client Error: Unauthorized for url: http://192.168.0.135:8282/MaterialInfoApi/StoreMaterialInfoData，请求 URL: http://192.168.0.135:8282/MaterialInfoApi/StoreMaterialInfoData，请求头: {'authorization': None}，请求体: {'MaterialCode': 'Automation01', 'MaterialName': '自动化测试物料01', 'materialCharacteristic': [{'label': '成品'}, {'label': '半成品'}, {'label': '物料'}], 'MaterialCategoryCode': 'DQJ', 'MaterialAttribute': 'SelfCreated', 'MaterialSpecification': '', 'OpSign': 1, 'MaintainerId': 10402, 'MaintainerName': 'CQ'}
2025-04-30 14:55:41,028 - get_token.py:[49] - [ERROR] - 请求发生错误: Invalid URL 'your_validation_url': No scheme supplied. Perhaps you meant http://your_validation_url?
2025-04-30 14:55:41,196 - get_token.py:[49] - [ERROR] - 请求发生错误: Invalid URL 'your_validation_url': No scheme supplied. Perhaps you meant http://your_validation_url?
2025-04-30 14:55:41,364 - get_token.py:[49] - [ERROR] - 请求发生错误: Invalid URL 'your_validation_url': No scheme supplied. Perhaps you meant http://your_validation_url?
2025-04-30 14:55:41,364 - get_token.py:[51] - [ERROR] - 多次尝试后仍无法获取有效的 authorization。
2025-04-30 15:07:46,801 - get_token.py:[45] - [WARNING] - 当前 authorization 无效，尝试重新获取...
2025-04-30 15:07:46,991 - get_token.py:[45] - [WARNING] - 当前 authorization 无效，尝试重新获取...
2025-04-30 15:07:47,205 - get_token.py:[45] - [WARNING] - 当前 authorization 无效，尝试重新获取...
2025-04-30 15:07:47,205 - get_token.py:[51] - [ERROR] - 多次尝试后仍无法获取有效的 authorization。
2025-04-30 15:09:46,145 - get_token.py:[57] - [WARNING] - 当前 authorization 无效，尝试重新获取...
2025-04-30 15:09:46,175 - get_token.py:[59] - [ERROR] - 解析响应 JSON 数据时发生错误。
2025-04-30 15:09:46,192 - get_token.py:[59] - [ERROR] - 解析响应 JSON 数据时发生错误。
2025-04-30 15:09:46,192 - get_token.py:[63] - [ERROR] - 多次尝试后仍无法获取有效的 authorization。
2025-04-30 15:11:49,971 - get_token.py:[58] - [WARNING] - 当前 authorization 无效，尝试重新获取...
2025-04-30 15:11:49,998 - get_token.py:[60] - [ERROR] - 解析响应 JSON 数据时发生错误。
2025-04-30 15:11:50,044 - get_token.py:[60] - [ERROR] - 解析响应 JSON 数据时发生错误。
2025-04-30 15:11:50,045 - get_token.py:[64] - [ERROR] - 多次尝试后仍无法获取有效的 authorization。
2025-04-30 16:26:38,483 - send_email.py:[101] - [ERROR] - 测试执行失败，错误信息: 
2025-04-30 16:26:48,118 - send_email.py:[210] - [INFO] - 钉钉发送状态码: 200
2025-04-30 16:28:27,603 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-04-30 16:28:27,603 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-04-30 16:28:27,776 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:28:27,776 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:28:27,776 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:28:27,801 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:28:27,801 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:28:27,801 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:28:27,801 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:28:31,411 - main1.py:[95] - [INFO] - 钉钉发送状态码: 200
2025-04-30 16:31:38,168 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-04-30 16:31:38,168 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-04-30 16:31:38,353 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:31:38,353 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:31:38,353 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:31:38,386 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:31:38,386 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:31:38,386 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:31:38,386 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:31:41,873 - main1.py:[155] - [INFO] - 钉钉发送状态码: 200
2025-04-30 16:35:16,774 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-04-30 16:35:16,774 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-04-30 16:35:16,948 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:35:16,948 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:35:16,948 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:35:16,971 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:35:16,971 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:35:16,971 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:35:16,971 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:35:20,462 - main1.py:[161] - [INFO] - 钉钉发送状态码: 200
2025-04-30 16:35:23,632 - main1.py:[146] - [ERROR] - 邮件发送失败: Connection unexpectedly closed
2025-04-30 16:42:35,207 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-04-30 16:42:35,207 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-04-30 16:42:35,407 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:42:35,407 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:42:35,407 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:42:35,439 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:42:35,439 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:42:35,439 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:42:35,439 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:42:41,508 - main1.py:[161] - [INFO] - 钉钉发送状态码: 200
2025-04-30 16:42:44,683 - main1.py:[146] - [ERROR] - 邮件发送失败: Connection unexpectedly closed
2025-04-30 16:50:36,179 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-04-30 16:50:36,179 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-04-30 16:50:36,486 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:50:36,486 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:50:36,486 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:50:36,520 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:50:36,520 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:50:36,520 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:50:36,520 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:50:52,042 - main1.py:[322] - [INFO] - 钉钉发送状态码: 200
2025-04-30 16:50:55,009 - main1.py:[303] - [ERROR] - 邮件发送失败: (535, b'Error: authentication failed')
2025-04-30 16:51:39,699 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-04-30 16:51:39,699 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-04-30 16:51:39,970 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:51:39,970 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:51:39,970 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 16:51:40,004 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:51:40,004 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:51:40,004 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:51:40,004 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 16:51:46,058 - main1.py:[322] - [INFO] - 钉钉发送状态码: 200
2025-04-30 16:51:49,590 - main1.py:[301] - [INFO] - 邮件发送成功
2025-04-30 17:01:26,520 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-04-30 17:01:26,520 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-04-30 17:01:26,723 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 17:01:26,723 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 17:01:26,723 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-04-30 17:01:26,761 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 17:01:26,761 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 17:01:26,761 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 17:01:26,761 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-04-30 17:01:32,522 - main1.py:[160] - [INFO] - 钉钉发送状态码: 200
2025-04-30 17:01:34,163 - main1.py:[141] - [INFO] - 邮件发送成功
