2025-05-07 11:09:27,982 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 11:09:27,982 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 11:09:28,328 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 11:09:28,328 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 11:09:28,328 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 11:09:28,380 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 11:09:28,380 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 11:09:28,380 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 11:09:28,380 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 11:09:43,488 - main1.py:[409] - [INFO] - 钉钉发送状态码: 200
2025-05-07 11:09:46,144 - main1.py:[360] - [INFO] - 邮件发送成功
2025-05-07 13:07:40,384 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 13:07:40,384 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 13:07:40,587 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 13:07:40,587 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 13:07:40,587 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 13:07:40,618 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 13:07:40,618 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 13:07:40,618 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 13:07:40,618 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 13:07:48,532 - main1.py:[191] - [INFO] - 钉钉发送状态码: 200
2025-05-07 13:07:48,532 - main1.py:[150] - [INFO] - 端口 8000 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:07:48,532 - main1.py:[150] - [INFO] - 端口 8001 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:07:48,532 - main1.py:[150] - [INFO] - 端口 8002 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:07:48,532 - main1.py:[150] - [INFO] - 端口 8003 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:07:48,532 - main1.py:[150] - [INFO] - 端口 8004 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:07:48,532 - main1.py:[150] - [INFO] - 端口 8005 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:07:48,532 - main1.py:[150] - [INFO] - 端口 8006 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:07:48,532 - main1.py:[150] - [INFO] - 端口 8007 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:07:48,532 - main1.py:[150] - [INFO] - 端口 8008 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:07:48,532 - main1.py:[150] - [INFO] - 端口 8009 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:07:48,532 - main1.py:[150] - [INFO] - 端口 8010 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:07:48,532 - main1.py:[150] - [INFO] - 端口 8011 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:07:48,532 - main1.py:[150] - [INFO] - 端口 8012 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:07:48,532 - main1.py:[150] - [INFO] - 端口 8013 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:07:48,532 - main1.py:[124] - [INFO] - 端口 8014 可用，尝试启动服务器...
2025-05-07 13:07:51,550 - main1.py:[143] - [INFO] - 端口 8014 可连接，生成报告链接...
2025-05-07 13:07:53,599 - main1.py:[170] - [INFO] - 邮件发送成功
2025-05-07 13:12:22,193 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 13:12:22,193 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 13:12:22,406 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 13:12:22,406 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 13:12:22,406 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 13:12:22,502 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 13:12:22,502 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 13:12:22,502 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 13:12:22,502 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 13:12:27,956 - main1.py:[191] - [INFO] - 钉钉发送状态码: 200
2025-05-07 13:12:27,956 - main1.py:[150] - [INFO] - 端口 8000 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:12:27,956 - main1.py:[150] - [INFO] - 端口 8001 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:12:27,956 - main1.py:[150] - [INFO] - 端口 8002 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:12:27,956 - main1.py:[150] - [INFO] - 端口 8003 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:12:27,956 - main1.py:[150] - [INFO] - 端口 8004 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:12:27,972 - main1.py:[150] - [INFO] - 端口 8005 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:12:27,972 - main1.py:[150] - [INFO] - 端口 8006 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:12:27,972 - main1.py:[150] - [INFO] - 端口 8007 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:12:27,972 - main1.py:[150] - [INFO] - 端口 8008 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:12:27,972 - main1.py:[150] - [INFO] - 端口 8009 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:12:27,972 - main1.py:[150] - [INFO] - 端口 8010 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:12:27,972 - main1.py:[150] - [INFO] - 端口 8011 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:12:27,972 - main1.py:[150] - [INFO] - 端口 8012 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:12:27,972 - main1.py:[150] - [INFO] - 端口 8013 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:12:27,972 - main1.py:[150] - [INFO] - 端口 8014 已被占用或不可用，继续尝试下一个端口...
2025-05-07 13:12:27,972 - main1.py:[124] - [INFO] - 端口 8015 可用，尝试启动服务器...
2025-05-07 13:12:31,000 - main1.py:[143] - [INFO] - 端口 8015 可连接，生成报告链接...
2025-05-07 13:12:33,025 - main1.py:[170] - [INFO] - 邮件发送成功
2025-05-07 14:35:27,350 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:35:27,350 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:35:27,522 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:35:27,522 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:35:27,522 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:35:27,553 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:35:27,553 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:35:27,553 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:35:27,553 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:36:20,379 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:36:20,379 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:36:20,551 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:36:20,551 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:36:20,551 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:36:20,582 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:36:20,582 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:36:20,582 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:36:20,582 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:42:19,325 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:42:19,325 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:42:19,497 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:42:19,497 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:42:19,497 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:42:19,529 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:42:19,529 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:42:19,529 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:42:19,529 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:42:23,373 - main1.py:[285] - [ERROR] - 发送钉钉通知失败: Invalid URL 'DINGTALK_WEBHOOK': No scheme supplied. Perhaps you meant http://DINGTALK_WEBHOOK?
2025-05-07 14:42:23,373 - main1.py:[357] - [INFO] - 钉钉发送状态码: 500
2025-05-07 14:48:09,500 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:48:09,500 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:48:09,668 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:48:09,668 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:48:09,668 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:48:09,699 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:48:09,699 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:48:09,699 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:48:09,699 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:48:12,852 - main1.py:[286] - [ERROR] - 发送钉钉通知失败: Invalid URL 'DINGTALK_WEBHOOK': No scheme supplied. Perhaps you meant http://DINGTALK_WEBHOOK?
2025-05-07 14:48:12,852 - main1.py:[358] - [INFO] - 钉钉发送状态码: 500
2025-05-07 14:54:56,437 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:54:56,437 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:54:56,609 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:54:56,609 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:54:56,609 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:54:56,640 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:54:56,640 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:54:56,640 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:54:56,640 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:55:00,637 - main1.py:[358] - [INFO] - 钉钉发送状态码: 200
2025-05-07 14:55:59,369 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:55:59,369 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:55:59,541 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:55:59,541 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:55:59,541 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:55:59,572 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:55:59,572 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:55:59,572 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:55:59,572 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:56:03,179 - main1.py:[357] - [INFO] - 钉钉发送状态码: 200
2025-05-07 14:56:56,568 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:56:56,568 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:56:56,740 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:56:56,740 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:56:56,740 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:56:56,771 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:56:56,771 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:56:56,771 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:56:56,771 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:57:00,158 - main1.py:[191] - [INFO] - 钉钉发送状态码: 200
2025-05-07 14:57:00,158 - main1.py:[124] - [INFO] - 端口 8016 可用，尝试启动服务器...
2025-05-07 14:57:03,181 - main1.py:[143] - [INFO] - 端口 8016 可连接，生成报告链接...
2025-05-07 14:57:04,122 - main1.py:[170] - [INFO] - 邮件发送成功
2025-05-07 14:58:46,213 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:58:46,213 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 14:58:46,385 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:58:46,385 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:58:46,385 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 14:58:46,416 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:58:46,416 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:58:46,416 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:58:46,416 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 14:58:49,973 - main1.py:[193] - [INFO] - 钉钉发送状态码: 200
2025-05-07 15:01:25,223 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 15:01:25,223 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 15:01:25,396 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 15:01:25,396 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 15:01:25,396 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 15:01:25,423 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 15:01:25,423 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 15:01:25,423 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 15:01:25,423 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 15:01:29,017 - main1.py:[194] - [INFO] - 钉钉发送状态码: 200
2025-05-07 15:01:59,166 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 15:01:59,166 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 15:01:59,355 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 15:01:59,355 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 15:01:59,355 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 15:01:59,370 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 15:01:59,370 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 15:01:59,370 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 15:01:59,370 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 15:02:02,835 - main1.py:[193] - [INFO] - 钉钉发送状态码: 200
2025-05-07 15:02:02,835 - main1.py:[126] - [INFO] - 端口 8017 可用，尝试启动服务器...
2025-05-07 15:02:05,855 - main1.py:[145] - [INFO] - 端口 8017 可连接，生成报告链接...
2025-05-07 15:02:06,965 - main1.py:[172] - [INFO] - 邮件发送成功
2025-05-07 16:39:09,062 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 16:39:09,062 - test_login.py:[24] - [INFO] - 本用例正在执行：test_login01。获取到的结果是：数据更新成功, 期望的结果是:数据更新成功，返回token
2025-05-07 16:39:09,276 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 16:39:09,276 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 16:39:09,276 - test_login.py:[41] - [INFO] - 本用例正在执行：test_login02。获取到的结果是：密码错误, 期望的结果是:账号错误，不返回token
2025-05-07 16:39:09,307 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 16:39:09,307 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 16:39:09,307 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 16:39:09,307 - test_login.py:[58] - [INFO] - 本用例正在执行：test_login03。获取到的结果是：用户不存在, 期望的结果是:用户不存在，不返回token
2025-05-07 16:39:18,732 - main1.py:[92] - [ERROR] - 发送钉钉通知失败: HTTPSConnectionPool(host='oapi.dingtalk.com', port=443): Max retries exceeded with url: /robot/send?access_token=727fef137b72ab2cabd7dfded3f55a95dbe8dc71c1bd1496f0673f3fc250d33c (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
2025-05-07 16:39:18,732 - main1.py:[193] - [INFO] - 钉钉发送状态码: 500
2025-05-07 16:39:18,732 - main1.py:[126] - [INFO] - 端口 8018 可用，尝试启动服务器...
2025-05-07 16:39:21,751 - main1.py:[145] - [INFO] - 端口 8018 可连接，生成报告链接...
2025-05-07 16:39:22,818 - main1.py:[172] - [INFO] - 邮件发送成功
